workflows:
  traccar-ios-swift:
    name: KMSTrack Manager (Swift)
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      # Étape 1: Vérification de la structure du projet
      - name: Verify project structure
        script: |
          echo "Structure du répertoire :"
          ls -la
          if [ ! -d "ios" ]; then
            echo "ERREUR : Le dossier 'ios' est introuvable"
            echo "Votre projet doit suivre la structure standard Flutter"
            exit 1
          fi

      # Étape 2: Initialisation Pod si nécessaire
      - name: Initialize Podfile if missing
        script: |
          cd ios
          if [ ! -f "Podfile" ]; then
            echo "Création d'un nouveau Podfile..."
            pod init
            # Configuration minimale Podfile
            cat <<EOF > Podfile
            platform :ios, '12.0'
            use_frameworks!
            target 'Runner' do
              # Ajoutez vos pods ici
            end
            EOF
          fi
          pod install

      # Étape 3: Configuration version build
      - name: Set build version
        script: |
          cd ios
          agvtool new-version -all $(date +%Y%m%d.%H%M)
          BUILD_NUMBER=$(agvtool what-version -terse)
          echo "Build number: $BUILD_NUMBER"
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      # Étape 4: Build Xcode
      - name: Build Xcode project
        script: |
          xcodebuild clean -workspace ios/Runner.xcworkspace -scheme Runner
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

    artifacts:
      - build/Runner.xcarchive
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - mbassijoel7@gmail.com
