workflows:
  traccar-ios-swift:
    name: Traccar Manager (Swift)
    environment:
      vars:
        XCODE_PROJECT: "Traccar.xcodeproj"  # Remplacez par votre nom de projet
        XCODE_SCHEME: "Traccar"             # Votre scheme principal
        DESTINATION: "generic/platform=iOS"  # Pour build générique
    scripts:
      # Étape 1: Installation des dépendances
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod setup

      # Étape 2: Configuration du projet Swift
      - name: Configure Swift project
        script: |
          cd ios
          pod install
          agvtool what-version -terse > /tmp/build_number.txt

      # Étape 3: Build non signé (Xcode)
      - name: Build unsigned .app
        script: |
          xcodebuild \
            -workspace "$XCODE_PROJECT/../$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination "$DESTINATION" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            clean build

      # Étape 4: Création d'un .zip installable
      - name: Package artifact
        script: |
          mkdir -p build/ios
          cd build/ios
          xcrun xcodebuild -exportArchive \
            -archivePath ../Build/Products/Release-iphoneos/$XCODE_SCHEME.xcarchive \
            -exportPath . \
            -exportOptionsPlist ../../exportOptions.plist
          zip -r Traccar_Manager_Unsigned.zip .

    artifacts:
      - build/ios/Traccar_Manager_Unsigned.zip
      - build/ios/*.ipa

    publishing:
      email:
        recipients:
          - mbassijoel7@gmail.com
      scripts:
        - name: Installation instructions
          script: |
            echo "Pour installer sur iPhone :"
            echo "1. Téléchargez AltStore (altstore.io)"
            echo "2. Transférez le .zip via Finder"
            echo "3. Installez via AltStore (valable 7 jours)"
