workflows:
  traccar-ios:
    name: KMSTrack Manager iOS
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "3.19.5"  # Version Flutter

    scripts:
      # Étape 1: Setup Flutter
      - name: Set up Flutter environment
        script: |
          flutter doctor -v
          flutter clean
          flutter pub get

      # Étape 2: Configuration iOS sans signature
      - name: iOS setup without signing
        script: |
          sudo gem install cocoapods
          cd ios
          pod install --repo-update || (rm -rf Pods Podfile.lock && pod install --repo-update)

      # Étape 3: Build IPA non signé
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                    -scheme "$XCODE_SCHEME" \
                    -configuration Release \
                    CODE_SIGN_IDENTITY="" \
                    CODE_SIGNING_REQUIRED=NO \
                    CODE_SIGNING_ALLOWED=NO

      # Étape 4: Préparation de l'artefact
      - name: Prepare artifact
        script: |
          mkdir -p build/ios/unsigned
          cp -r build/ios/ipa/*.ipa build/ios/unsigned/
          zip -r build/ios/unsigned_app.zip build/ios/unsigned

    artifacts:
      - build/ios/unsigned_app.zip  # Contient l'IPA non signé
      - build/ios/ipa/*.ipa         # Fichier IPA brut

    publishing:
      email:
        recipients:
          - mbassijoel7@gmail.com
      scripts:
        - name: Notify completion
          script: echo "Build iOS non signé terminé. Téléchargez le fichier .zip depuis les artefacts."
