workflows:
  traccar-ios:
    name: KMSTrack Manager iOS
    environment:
      groups:
        # Ajoutez vos variables sensibles ici (ex: certificats)
        - app_store_credentials # Optionnel pour la publication
      vars:
        BUNDLE_ID: "com.example.traccar.manager" # Remplacez par votre Bundle ID
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "3.19.5" # Version de Flutter requise
    scripts:
      # Installation Flutter et dépendances
      - name: Set up Flutter
        script: |
          flutter doctor -v
          flutter pub get

      # Résolution des problèmes iOS/Pods
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          pod setup

      - name: Install Pods with Retry
        script: |
          cd ios
          pod install --repo-update || (rm -rf Pods Podfile.lock && pod install --repo-update)

      # Build iOS
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
          cd ios
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -archivePath Runner.xcarchive archive

      # Optionnel : Signature automatique (si certificats disponibles)
      - name: Sign IPA (if credentials)
        script: |
          xcodebuild -exportArchive -archivePath Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath .
        condition: app_store_credentials

    artifacts:
      - build/ios/ipa/*.ipa
      - Runner.xcarchive

    publishing:
      app_store_connect: # Nécessite un compte développeur Apple
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - mbassijoel7@gmail.com
